<?php
    $lang = array(
	    'en' => array(
			'title' => 'My shop',
			'user' => 'Username',
      'password'=>'Password',
      'nume'=>'First Name',
      'prenume'=>'Last Name',
      'registration'=>'Sing In',
      'login'=>'Login',
      'contact'=>'Contact',
      'nrTel'=>'Phone Number',
      'eyes'=>'Eyes',
      'lips'=>'Lips',
      'face'=>'Face',
      'home'=>'Home',
      'cart'=>'My Cart',
      'emptyAllCart'=>'Delete All Products',
      'emptyCart'=>'There is not any products',
      'delProduct'=>'Delete Product',
      'orderdetails'=>"Order Details",
      'priceProduct'=>'Products Price',
      'priceTravel'=>'Delivery Price',
      'finish'=>'Confirm',
      'back'=>'Back',
      'showOrders'=>'Vezi Comenzi',
      'addProducts'=>'Add Product',
      'uploadPhoto'=>'Upload Image',
      'managerProducts'=>'Manager Product'
			),

		'ro' => array(
			'title' => 'Magazinul meu',
			'user' => 'Utililizator',
      'password'=>'Parola',
      'nume'=>'Nume',
      'prenume'=>'Prenume',
      'registration'=>'Inregistrare',
      'login'=>'LogIn',
      'contact'=>'Contact',
      'nrTel'=>'Numar Telefon',
      'eyes'=>'Ochi',
      'lips'=>'Buze',
      'face'=>'Fata',
      'home'=>'Acasa',
      'cart'=>'Cosul Meu',
      'emptyAllCart'=>'Sterge Toate Produsele',
      'emptyCart'=>'Nu exista niciun produs',
      'delProduct'=>'Sterge Produs',
      'orderdetails'=>'Sumar Comanda',
      'priceProduct'=>'Pret Produse',
      'priceTravel'=>'Pret Livrare',
      'finish'=>'Confirma',
      'back'=>'Inapoi',
      'showOrders'=>'Vezi Comenzi',
      'addProducts'=>'Adauga Produs',
      'uploadPhoto'=>'Adauga Imagine',
      'managerProducts'=>'Gestioneaza Produse'
    )
	);
?>
